name: ci host - qbt bootstrap docker container
description: An action to install qemu user static for cross-compilation via apt on the host runner.
inputs:
  distinct_id:
    description: "Distinct id"
    required: false
  use_host_env:
    description: "Use host env"
    required: false
    default: "false"
  container_name:
    description: "Multiarch container name"
    required: true
  os_id:
    description: "Operating system id"
    required: true
  os_version_id:
    description: "Operating system version id"
    required: true
  custom_docker_commands:
    description: "Custom commands (space-separated)"
    required: false
    default: ""
  additional_alpine_apps:
    description: "Additional Alpine applications to install (space-separated)"
    required: false
    default: ""
  additional_debian_apps:
    description: "Additional Debian/Ubuntu applications to install (space-separated)"
    required: false
    default: ""
  uid:
    description: "Set the user id"
    required: false
    default: "gh"
  gid:
    description: "Set the user group"
    required: false
    default: "1001"
outputs:
  container_info:
    description: "The name provided for the container"
    value: ${{ steps.container_info.outputs.container_name }}
runs:
  using: "composite"
  steps:
    - name: Host - Dump Github env to container env ${{ inputs.distinct_id }}
      if: inputs.use_host_env == 'true'
      shell: sh
      run: env >> env.custom

    - name: Host - Create docker ${{ inputs.container_name }} container ${{ inputs.distinct_id }}
      id: container_info
      env:
        inputs_container_name: ${{ inputs.container_name }}
        inputs_os_id: ${{ inputs.os_id }}
        inputs_os_version_id: ${{ inputs.os_version_id }}
        inputs_custom_docker_commands: ${{ inputs.custom_docker_commands }}
        inputs_additional_alpine_apps: ${{ inputs.additional_alpine_apps }}
        inputs_additional_debian_apps: ${{ inputs.additional_debian_apps }}
        inputs_uid: ${{ inputs.uid }}
        inputs_gid: ${{ inputs.gid }}
      shell: sh
      if: inputs.os_id != ''
      run: |
        # We create an container for cross-compilation with a user named gh which has same id as runner ${inputs_gid} and provide sudo access

        # Build docker command with conditional env-file
        docker_cmd="docker run --name ${inputs_container_name} -it -d"

        # Only add env-file if file exists
        if [ -f env.custom ]; then
          docker_cmd="$docker_cmd --env-file env.custom"
        fi

        # Only add LANG if OS is debian/ubuntu (supports repo-qualified names like something/debian)
        case "$inputs_os_id" in
          debian|*/debian|ubuntu|*/ubuntu)
            docker_cmd="$docker_cmd -e LANG=C.UTF-8"
            ;;
        esac

        docker_cmd="$docker_cmd -w /home/${inputs_uid} -v ${{ github.workspace }}:/home/${inputs_uid} ${inputs_custom_docker_commands} ${inputs_os_id}:${inputs_os_version_id}"

        # Execute the docker command
        eval $docker_cmd

        # Create the user ${inputs_uid} with the id ${inputs_gid}:${inputs_gid} which is the same as the runner user id and group id.
        case "$inputs_os_id" in
          alpine|*/alpine)
            docker exec ${inputs_container_name} sh -c "adduser -h /home/${inputs_uid} -Ds /bin/bash -u ${inputs_gid} ${inputs_uid}"
            docker exec ${inputs_container_name} sh -c "apk update --no-cache"
            docker exec ${inputs_container_name} sh -c "apk add -u --no-cache sudo bash ${inputs_additional_alpine_apps}"
            docker exec ${inputs_container_name} sh -c "apk upgrade --no-cache"
            ;;
        esac

        case "$inputs_os_id" in
          debian|*/debian|ubuntu|*/ubuntu)
            docker exec ${inputs_container_name} sh -c "useradd -ms /bin/bash -u ${inputs_gid} ${inputs_uid}"
            docker exec ${inputs_container_name} sh -c "apt-get update"
            docker exec ${inputs_container_name} sh -c "apt-get install -y sudo ${inputs_additional_debian_apps}"
            docker exec ${inputs_container_name} sh -c "apt-get upgrade -y"
            ;;
        esac

        case "$inputs_os_id" in
          alpine|*/alpine|debian|*/debian|ubuntu|*/ubuntu)
            # Allow the user ${inputs_uid} to run sudo without password prompt: docker exec -u ${inputs_uid}:${inputs_uid} ${inputs_container_name} sudo ls
            docker exec ${inputs_container_name} sh -c 'printf "%s" "'"${inputs_uid}"' ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/'"${inputs_uid}"''
            ;;
        esac

        printf '%b\n' "container_name=${inputs_container_name}" >> $GITHUB_OUTPUT
